### PR TITLE
added groupby object and a histogram of GINI index

### PR DESCRIPTION
**Pull request by Kiwibp**
Let me know if I'm doing this right :) I can create a bar chart as well if you'd like.

### CODE REVIEW

**Comment by lotusflyer** [comment]
Hi Keenan! Looks good but I think we could simplify it. We have two redundant columns -- the first is "name" and the second is "county". I believe that each DF row is unique and represents one county. 

The groupby is sweet! -- you make sure that we are combining each counties' observation into a mean score but I think redundant.

 I might propose the following.
- add a "data cleaning" section at the top right after the initial print the the head of the DF. 
- drop the "name" column
- make county the index

Then we can do a histogram on the DF and play with the binning (histograms are really sensitive to the binning)

Also my bad -- should have put the %matplotlib inline magic at the top. I think its best practice to put all the imports and magics at the top.

**Comment by lotusflyer** [comment]
Let me know what you think!

**Comment by lotusflyer** [comment]
Hi -- I pushed a branch (simple-hist) to demonstrate what I meant -- feel free to take a peek if you like. I will trash it when you revise your pull and we merge.

**Comment by Kiwibp** [comment]
Thanks George! Ill take a look and send over some updates tonight or tomorrow.

**Comment by lotusflyer** [comment]
Excellent. What you did works fine — just some tweaking on the principle of simpler is better.

 But the groupby first was a good call except we have a single observation in each category

Best regards


George Collier

**Comment by Kiwibp** [comment]
Can I pull your edits that you have in simple-hist branch into my test-branch? I tried to do that and got a merge conflict error and have been trying work through it but I am lost. I could manually just copy and paste the added Data Cleaning and Exploratory Stats sections you created in your simple-hist branch but Im assuming there is a better way to do it.  

Im confused if I can and should use pull upstream remote command to merge updates you made on a branch of yours or if I can only merge updates from the your master?

**Comment by lotusflyer** [comment]
Hi Keenan, my thinking was that you would manually add what you found useful from my branch as I put it together to show what I meant (NB there is a bug in the sort statement -- I forgot to say what column to sort on). 

Not surprised there are merge conflicts -- I didn't just add code -- I changed a bunch of it.

I'll bet you anything that your upstream remote points at the master and so I would need to merge my branch into the master and then you could pull it. But I wasn't trying to step on your pull request. I wanted to show you what I meant. So copy and paste into your pull request and push it to your branch. Then we can merge. If there are conflicts I can review your version and just take it rather merging.

Lets try that way first?

**Comment by lotusflyer** [comment]
Hmm I checked and I can merge my branch into the master without conflicts.

**Pull request closed without merging**
